---
- name: Render VMX configs for all hosts
  hosts: vmx
  connection: local
  gather_facts: false

  tasks:
    - name: Render base VMX config for this host
      ansible.builtin.template:
        src: "{{ playbook_dir }}/templates/vmx/vmx-template-full.j2"
        dest: "{{ playbook_dir }}/render/{{ inventory_hostname }}_basic.conf"
